import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="navbarContainer">
          <Link href="/" className='navItem'>HOME</Link>
          {/* <Link href="/dogos" className='navItem'>DOGOS</Link> */}
          <Link href="/halo-players" className='navItem'>Halo Players</Link>
          <Link href="/halo-ranks" className='navItem'>Halo Ranks</Link>
          <Link href="/halo-maps" className='navItem'>Halo Maps</Link>
          <Link href="/halo-medals" className='navItem'>Halo Medals</Link>
        </div>

        <div className='homebox'>
          <div className="text">
            <h1 className='textwhite'>Microsoft 343 Studios - HALO 5 API </h1>
            
            <h3 className='textwhite2'>On navbar click on said link to view data from API.</h3>
            <ul>
              <li>Search by Halo Players</li>
              <li>Search the Halo Ranks</li>
              <li>Search the Halo Maps</li>
              <li>Search the Halo Medals</li>
            </ul>
            <h4 className='textwhite2'>All data is from Microsoft 343</h4>
          </div>

        </div>


      </div>
    </>
  )
}
